
# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  mvn_deploy:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      JFROG_BUILD_NUMBER: 1524548
      DESIRED_MAVEN_VERSION: 3.6.3
      GUARDIAN_GIT_URI: "https://github.com/gravitee-lab/gravitee-gateway"
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Git Clone the maven project used to maven deploy to JFROG : the \"Guardian maven project\""
          command: |
                    mkdir -p $PWD/guard-shift
                    git clone "${GUARDIAN_GIT_URI}" $PWD/guard-shift
      - run:
          name: "Maven clean install the Guardian maven project"
          command: |
                    echo "Run Maven Tests"
                    export MVN_DOCKER_IMAGE="maven:${DESIRED_MAVEN_VERSION}-openjdk-16 "
                    export MAVEN_COMMAND="mvn clean install"
                    echo "MAVEN_COMMAND=[${MAVEN_COMMAND}]"
                    docker run -it --rm -v "$PWD/guard-shift":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven ${MVN_DOCKER_IMAGE} ${MAVEN_COMMAND}

      - run: # print the name of the branch we're on
          name: "Maven Deploy the Gravitee Component to Central Maven Repo : JFrog"
          command: |
                    echo "Run Maven Deploy using JFrog Maven Plugin"
                    export MVN_DOCKER_IMAGE="maven:${DESIRED_MAVEN_VERSION}-openjdk-16 "
                    #
                    # see https://github.com/jfrog/project-examples/tree/master/artifactory-maven-plugin-example
                    export JFROG_USERNAME=$(secrethub read gravitee-lab/cicd-infra/dev/jfrog/username)
                    export JFROG_SECRET=$(secrethub read gravitee-lab/cicd-infra/dev/jfrog/password)
                    echo "JFROG_USERNAME=[${JFROG_USERNAME}]"
                    # echo "JFROG_SECRET=[${JFROG_SECRET}]"
                    export MAVEN_COMMAND="mvn deploy -Dusername=${JFROG_USERNAME} -Dpassword=${JFROG_SECRET} -Dbuildnumber=${JFROG_BUILD_NUMBER}"
                    echo "MAVEN_COMMAND=[${MAVEN_COMMAND}]"
                    docker run -it --rm -v "$PWD/guard-shift":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven ${MVN_DOCKER_IMAGE} ${MAVEN_COMMAND}

workflows:
  version: 2.1
  weekly_guard_shift:
    # triggers:
      # - schedule:
          # cron: "0 0 * * *"
          # filters:
            # branches:
              # only:
                # - master
                # - beta
            # tags:
              # only:
                # - stable-latest
    jobs:
      - mvn_deploy:
          context: cicd-orchestrator
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - stable-latest
